### ISSUE TITLE
安装完插件启动QQ时出错...

### ISSUE THREAD

**Issue by QQ804218** [mo-jinran/chii-devtools#5]
![image](https://github.com/mo-jinran/chii-devtools/assets/67571282/4cee4a38-70ff-4e4d-a0cf-8d80e16f0853)

**Comment by mo-jinran** [comment]
你需要下载Release中的 [chii-devtools.zip](https://github.com/mo-jinran/chii-devtools/releases/download/1.0.0/chii-devtools.zip) 或者在安装 node.js 运行 npm install 安装依赖
